name: game
description: Learning Curve Mobile App.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  english_words: ^3.1.5
  http: ^0.12.1
  path_provider: ^1.6.11
  flutter_spinkit: "^2.1.0"
  giffy_dialog: ^1.7.0
  rflutter_alert: ^1.0.3
  flutter_tts: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pangolin
      fonts:
        - asset: fonts/Pangolin-Regular.ttf